package com.mtgcompanion.app.tester

/** One thing a tester build asks to be tried: what changed, and how to see it. */
data class TesterNote(val id: String, val title: String, val howToTry: String)

/**
 * What's new in this tester build — shown the first time it opens, each with "Works" and "Problem".
 * Rewritten for every build: it's the list of what to look at before the change goes to the real app.
 */
val TESTER_NOTES: List<TesterNote> = listOf(
    TesterNote(
        "scan-memory",
        "Scanner: learns from your corrections",
        "1) Open Scan and scan a basic land (say a Plains) whose set code can't be read, so its row says \"Best guess · pick art\". Open View list, tap Best guess · pick art and pick a different Plains. 2) Take that row off, scan the same Plains again: it still comes in as the usual one (a printing is only preferred once picked twice). Pick the same printing again. 3) Scan it a third time: it comes in as your printing straight away, the status ends \"· learned from your correction\", and the row has a gold \"Learned\" tag. 4) Tap Learned: \"You corrected this before…\" with Forget it and Pick another printing. Pick another printing → a different one: it's remembered instead (and needs picking twice again). 5) A misread: scan a card whose small print reads (the row has no Best guess). Tap its set name under the card name to change the printing, pick another. Scan the same card again: it comes in as your pick the very first time, tagged Learned. Pick the original printing back on that row: next scan goes by the small print again. 6) Sort a pile: start a sort and scan a card whose small print reads; Wrong card? › Pick the printing, pick another. Take the next copy of that card (or Undo and show it again): it goes in as your pick and the panel shows a gold Learned chip after Wrong card?; tap it › Forget it. For a card whose set won't read, pick the same printing on two copies; the third is put right. 6b) A different card: on a scan-list row tap its set line (or Best guess · pick art) › It's a different card, or in Sort a pile Wrong card? › It's a different card. Type a few letters, pick the name, then its printing: the row (or the sort's card) becomes that card — in Sort a pile it moves to that card's pile, with the count and Undo still right. Scan the same card again the same way: it comes in as the card you named, tagged Learned. 7) Settings › Scanner › Learned corrections (N): tap to open — each line says what was read (\"Plains, set unread\" or the title and set as read), → the card it becomes, and how often it was corrected and used; Forget removes one, Forget all (tap twice) clears the list. 8) Signed in on two devices: a correction made on one shows in the other's list after a sync; Forget on one removes it on the other. 9) Settings › Data and speed › Reset collection: \"Cards only\" keeps the learned corrections, \"Collection\" and \"Everything\" clear them (the wording of both says so)."
    ),
    TesterNote(
        "deck-upgrade",
        "Decks: upgrade with my cards",
        "Open a Commander deck you've built (with a commander) whose binders/boxes/Unsorted hold some cards that aren't in it. 1) Open the Suggestions tab: \"Upgrade with my cards\" is the first section. After \"Looking through your collection…\" it lists swaps — the deck's card (orange) → a card you own (gold) — and above them a line like \"5 upgrades from your cards · $12.40 of cards you already own · pull from 3 places\" (the money part is left out when the cards have no price). 2) Check a row: both cards do the same job (ramp for ramp, removal for removal…); the reason reads like \"Both are ramp; Arcane Signet is in 61% of Krenko decks, Wayfarer's Bauble in 22%.\"; under it is where the new card is (\"Red box › Artifacts\", \"Trade binder p3 s5\", \"Unsorted\", or \"in Atraxa deck\" when another deck has your only copy) and the price difference. The commander, lands, combo pieces and cards you tagged \"keep\" are never offered as cuts; cards outside the commander's colours or not legal in the format are never offered as adds; a card you marked as a cut is offered first. 3) Tap Swap now: a message says \"X in for Y — on the pull list (where)\"; the cut card is on Considering, the new card is in the deck, and the deck's menu › Pull list shows it with its place. Tap Undo on that message: the deck is exactly as before — the cut card back in its place (and back out of Considering), the new card gone from the deck and the pull list, and for a physical deck the cut card's copy back out of Unsorted. Tap Consider on another row: the new card goes on Considering, the deck is unchanged. Tap Not this one: the row goes, and stays gone after leaving and reopening the deck; \"Bring back N dismissed\" undoes it. 4) Untick a row and tap Apply all checked (n): only the ticked swaps are made, and one Undo takes them all back. 5) A deck at bracket 2–3 with a Game Changer (or combo piece) you own: the footer shows \"Show N that would raise the bracket\"; tap it — those rows have an orange outline and \"Would move the deck to bracket 4\" (or 3), and are unticked. 6) Deck menu (⋮) › Upgrade with my cards: jumps to the Suggestions tab. 7) Turn on airplane mode and reopen the deck's Suggestions: a note says EDHREC can't be reached and swaps are matched by role and EDHREC rank (\"Consider ranks #900 on EDHREC, Divination #9,000\"). A Modern/Standard deck works the same way with no bracket and no commander percentages. Compare with manabind.com: the same deck and collection should give the same swaps."
    )
)
